kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  labels:
    wireguard: disabled
- role: worker
  image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  labels:
    wireguard: disabled
- role: worker
  image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  labels:
    egress: wireguard
    wireguard: enabled
    # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 31001
    hostPort: 31001
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "192.168.1.28"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: UDP
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  
