apiVersion: v1
kind: Pod
metadata:
 name: wireguard
 labels:
   egress: wireguard  
spec:
  nodeSelector:
    egress: wireguard 
  containers:
  - name: wireguard-node-endpoint
    image: "wireguard-tunnel:0.1"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    env:
    - name: TUNNEL_MODE
      value: node
    ports:
    - containerPort: 31001    
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    egress: wireguard
  name: wireguard-service
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31001
    targetPort: 31001
    port: 31001
    protocol: UDP
  selector:
    egress: wireguard
  type: NodePort

